"use client";

import { useState } from "react";
import FadeInOnView from "@/components/ui/FadeInOnView";

export default function BudgetBreakdownSection() {
  return (
    <div className="mt-16 pt-16 border-t border-[--color-hairline] space-y-12">
      
      {/* ── Section 1: What we Spend vs What we Contribute (Image 3 Style) ── */}
      <div>
        <h3 className="text-lg font-bold text-[--color-ink] tracking-tight mb-2">
          What we build: National Costs vs Contributions
        </h3>
        <p className="text-sm text-[--color-muted] leading-relaxed max-w-2xl mb-8">
          Comparing the financial scale of national maintenance costs against primary economic contributors. This balances infrastructure expenditure against taxes, exports, and diaspora investments.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Costs Column */}
          <div className="space-y-6">
            <h4 className="text-xs font-semibold text-[--color-muted] uppercase tracking-wider border-b border-[--color-hairline] pb-2">
              What India Spends (Annual Outflows)
            </h4>
            
            <div className="space-y-4">
              <div>
                <div className="text-2xl font-bold text-[--color-ink]">$135B</div>
                <div className="text-[11px] font-semibold text-red-600 uppercase tracking-tight mt-0.5">Infrastructure Allocation</div>
                <p className="text-xs text-[--color-muted] mt-1">
                  Budgeted capital expenditure for highways, railways, and urban infrastructure developments.
                </p>
              </div>

              <div>
                <div className="text-2xl font-bold text-[--color-ink]">$120B</div>
                <div className="text-[11px] font-semibold text-red-600 uppercase tracking-tight mt-0.5">Crude Oil Imports</div>
                <p className="text-xs text-[--color-muted] mt-1">
                  The primary external dependency cost, placing pressure on the national current account deficit.
                </p>
              </div>

              <div>
                <div className="text-2xl font-bold text-[--color-ink]">$95B</div>
                <div className="text-[11px] font-semibold text-red-600 uppercase tracking-tight mt-0.5">Public Debt Interest</div>
                <p className="text-xs text-[--color-muted] mt-1">
                  Annual payments servicing national domestic and external debt accumulations.
                </p>
              </div>

              <div>
                <div className="text-2xl font-bold text-[--color-ink]">$48B</div>
                <div className="text-[11px] font-semibold text-red-600 uppercase tracking-tight mt-0.5">National Subsidies</div>
                <p className="text-xs text-[--color-muted] mt-1">
                  Government spend on food safety, agricultural fertilizers, and rural support schemes.
                </p>
              </div>
            </div>
          </div>

          {/* Contributions Column */}
          <div className="space-y-6">
            <h4 className="text-xs font-semibold text-[--color-muted] uppercase tracking-wider border-b border-[--color-hairline] pb-2">
              What India Earns (Annual Inflows)
            </h4>

            <div className="space-y-4">
              <div>
                <div className="text-2xl font-bold text-green-600">$310B</div>
                <div className="text-[11px] font-semibold text-green-700 uppercase tracking-tight mt-0.5">Taxes Collected</div>
                <p className="text-xs text-[--color-muted] mt-1">
                  Total revenue collected from direct income taxes and indirect Goods & Services Tax (GST).
                </p>
              </div>

              <div>
                <div className="text-2xl font-bold text-green-600">$185B</div>
                <div className="text-[11px] font-semibold text-green-700 uppercase tracking-tight mt-0.5">IT & Services Exports</div>
                <p className="text-xs text-[--color-muted] mt-1">
                  Net export value generated by technology services, offshoring operations, and consulting.
                </p>
              </div>

              <div>
                <div className="text-2xl font-bold text-green-600">$125B</div>
                <div className="text-[11px] font-semibold text-green-700 uppercase tracking-tight mt-0.5">Diaspora Remittances</div>
                <p className="text-xs text-[--color-muted] mt-1">
                  Net inbound funds sent by non-resident Indians (NRIs) back to families, leading global inflows.
                </p>
              </div>

              <div>
                <div className="text-2xl font-bold text-green-600">$71B</div>
                <div className="text-[11px] font-semibold text-green-700 uppercase tracking-tight mt-0.5">Foreign Direct Investment</div>
                <p className="text-xs text-[--color-muted] mt-1">
                  Annual equity inflows from international corporations investing directly into Indian markets.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Section 2: Where the Rupee Goes (Image 2 & 4 Style Progress Bars) ── */}
      <div>
        <h3 className="text-lg font-bold text-[--color-ink] tracking-tight mb-2">
          Where the Money Goes: Central Outlay Breakdown
        </h3>
        <p className="text-sm text-[--color-muted] leading-relaxed max-w-2xl mb-6">
          A proportional breakdown of how the central government allocates every single rupee of national revenue.
        </p>

        <div className="bg-[--color-bg] border border-[--color-hairline] rounded-2xl p-5 space-y-4 max-w-3xl">
          <div className="text-[10px] font-semibold text-[--color-muted] uppercase tracking-wider">
            Union Budget Expenditure Breakdown
          </div>
          
          <div className="space-y-3">
            {[
              { label: "Interest Payments (Servicing Debt)", value: 20, color: "bg-[#FF6B35]" },
              { label: "States' Share of Taxes & Duties", value: 20, color: "bg-[#FF9933]" },
              { label: "Central Sector Schemes", value: 16, color: "bg-[#3B82F6]" },
              { label: "Centrally Sponsored Schemes", value: 9, color: "bg-[#60A5FA]" },
              { label: "Finance Commission Transfers", value: 8, color: "bg-[#93C5FD]" },
              { label: "Defense Outlays", value: 8, color: "bg-neutral-600" },
              { label: "Other Expenditure", value: 9, color: "bg-neutral-400" },
              { label: "Subsidies (Food, Fertilisers)", value: 6, color: "bg-[#22C55E]" },
              { label: "Pensions", value: 4, color: "bg-[#86EFAC]" },
            ].map(item => (
              <div key={item.label} className="space-y-1">
                <div className="flex justify-between text-xs font-semibold">
                  <span className="text-[--color-ink]">{item.label}</span>
                  <span className="text-[--color-muted] tabular-nums">{item.value}%</span>
                </div>
                <div className="w-full h-2 bg-neutral-200/50 rounded-full overflow-hidden">
                  <div className={`h-full ${item.color} rounded-full`} style={{ width: `${item.value}%` }} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

    </div>
  );
}
